### ISSUE TITLE
Refer to image created a step before

### ISSUE THREAD

**Issue by kenshuri** [floms/action-caprover#4]
Hello,

I'm very new with github actions, caprover and docker images so I might be asking very stupid questions, sorry if it is the case. I searched for a good amount of time and could not understand it by myself...

So, I'm trying to deploy to caprover a docker image built just before in my github action. Please see below my `.yml` file:
```
name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:latest
    
    - name: Print image names
      run: docker images -q my-image-name
      
    - name: Deploy image
      uses: floms/action-caprover@v1
      with:
        host: '${{ secrets.CAPROVER_SERVER }}'
        password: '${{ secrets.CAPROVER_PASSWORD }}'
        app: '${{ secrets.APP_NAME }}'
        image: my-image-name:latest
```

The `Build the Docker image` step was successful, but the `Deploy image` one was not. The error message I got was:
```
Build started for ***
An explicit image name was provided (my-image-name:latest). Therefore, no build process is needed.
Pulling this image: my-image-name:latest This process might take a few minutes.
Build has failed!
----------------------
Deploy failed!
Error: (HTTP code 404) unexpected - pull access denied for my-image-name, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
```

Based on the error message, I believe I do not give the correct image name to your `floms/action-caprover@v1` action. It is why I created step 2 `Print image names` to try and understand better what is the *real name* of the image created. I tried several solutions for the foeld `image`, but all resulted to an error...

Please let me know if this issue should not be filled here as it might be more a question for stackoverflow as an issue with your action...

Thanks for the all the help you could provide
